#!/usr/bin/env bash
# Backup GitHub Copilot Chat transcripts for THIS repo into conversations/.
#
# What it does (idempotent):
#   1. Finds Copilot Chat transcripts under VS Code's workspaceStorage whose
#      workspace.json folder == this repo's root.
#   2. Copies each raw transcript (gzipped) into conversations/raw/
#   3. Converts each to readable Markdown in conversations/markdown/
#      via copilot_jsonl_to_markdown.py
#   4. Regenerates conversations/INDEX.md (covers both Claude + Copilot archives)
#   5. If anything changed, git add + commit + push
#
# Safe to run repeatedly. A transcript is only re-synced when its source file
# is newer than the stored copy.
#
# Exit codes: 0 success · 1 setup error · 2 git push failed

set -euo pipefail

# ── Resolve repo root from this script's own location ──────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BRANCH="${BRANCH:-main}"
LOG_FILE="${LOG_FILE:-$SCRIPT_DIR/copilot-backup.log}"

# VS Code chat storage root (override with CODE_STORAGE if you use Insiders, etc.)
CODE_STORAGE="${CODE_STORAGE:-$HOME/Library/Application Support/Code/User/workspaceStorage}"

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg"
  echo "$msg" >> "$LOG_FILE"
}

mkdir -p "$(dirname "$LOG_FILE")"
log "── Copilot backup run starting ──"

command -v python3 >/dev/null 2>&1 || { log "ERROR: python3 not on PATH"; exit 1; }
command -v git >/dev/null 2>&1     || { log "ERROR: git not on PATH"; exit 1; }
[[ -d "$REPO_ROOT/.git" ]]         || { log "ERROR: not a git repo: $REPO_ROOT"; exit 1; }
[[ -d "$CODE_STORAGE" ]]           || { log "ERROR: VS Code storage not found: $CODE_STORAGE"; exit 1; }

cd "$REPO_ROOT"

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$CURRENT_BRANCH" != "$BRANCH" ]]; then
  log "WARNING: on branch $CURRENT_BRANCH, expected $BRANCH. Will commit but not push."
  PUSH_ENABLED=false
else
  PUSH_ENABLED=true
fi

if $PUSH_ENABLED; then
  log "Pulling latest from origin/$BRANCH..."
  git pull --rebase --autostash origin "$BRANCH" >> "$LOG_FILE" 2>&1 \
    || log "WARNING: git pull failed; continuing with local state"
fi

RAW_DIR="$REPO_ROOT/conversations/raw"
MD_DIR="$REPO_ROOT/conversations/markdown"
mkdir -p "$RAW_DIR" "$MD_DIR"

# The repo's own folder URI, as VS Code records it in workspace.json
REPO_URI="file://$REPO_ROOT"

COUNT=0
NEW_OR_UPDATED=0

# Iterate every workspace's Copilot transcript folder; keep only those whose
# workspace.json points at THIS repo. This is robust to VS Code changing the
# opaque storage hash.
while IFS= read -r -d '' tdir; do
  ws_json="$(dirname "$(dirname "$tdir")")/workspace.json"
  [[ -f "$ws_json" ]] || continue
  folder="$(python3 -c "import json,sys; print(json.load(open(sys.argv[1])).get('folder',''))" "$ws_json" 2>/dev/null || echo "")"
  # Normalize a possible trailing slash
  folder="${folder%/}"
  [[ "$folder" == "$REPO_URI" ]] || continue

  while IFS= read -r -d '' jsonl_file; do
    COUNT=$((COUNT + 1))
    session_id="$(basename "$jsonl_file" .jsonl)"
    mtime_date="$(date -r "$jsonl_file" '+%Y-%m-%d')"
    prefix="${mtime_date}_copilot_${session_id:0:8}"

    raw_dst="$RAW_DIR/${prefix}.jsonl.gz"
    md_dst="$MD_DIR/${prefix}.md"

    needs_update=false
    if [[ ! -f "$raw_dst" ]]; then
      needs_update=true
    elif [[ "$jsonl_file" -nt "$raw_dst" ]]; then
      needs_update=true
    fi

    if $needs_update; then
      gzip -n -c "$jsonl_file" > "$raw_dst" || { log "WARNING: gzip failed for $jsonl_file"; continue; }
      python3 "$SCRIPT_DIR/copilot_jsonl_to_markdown.py" "$raw_dst" "$md_dst" >> "$LOG_FILE" 2>&1 \
        || { log "WARNING: conversion failed for $jsonl_file"; continue; }
      NEW_OR_UPDATED=$((NEW_OR_UPDATED + 1))
      log "Synced: $prefix"
    fi
  done < <(find "$tdir" -maxdepth 1 -type f -name '*.jsonl' -print0)
done < <(find "$CODE_STORAGE" -maxdepth 3 -type d -name transcripts -path '*/GitHub.copilot-chat/*' -print0)

log "Found $COUNT transcript(s) for this repo, $NEW_OR_UPDATED new or updated."

# ── Regenerate INDEX.md (covers every .md in markdown/, Claude + Copilot) ──
INDEX="$REPO_ROOT/conversations/INDEX.md"
{
  echo "# Conversation Archive Index"
  echo ""
  echo "_Auto-generated by \`backup_copilot_conversations.sh\`. Last updated: $(date '+%Y-%m-%d %H:%M:%S %Z')_"
  echo ""
  echo "| Date | Session | Size | Markdown | Raw JSONL |"
  echo "|------|---------|------|----------|-----------|"
  find "$MD_DIR" -maxdepth 1 -name '*.md' -print0 2>/dev/null \
    | xargs -0 -I{} basename {} .md \
    | sort -r \
    | while IFS= read -r base; do
        md_file="$MD_DIR/${base}.md"
        date_part="${base%%_*}"
        sess_part="${base#*_}"
        size_bytes=$(wc -c < "$md_file" 2>/dev/null || echo 0)
        if [[ "$size_bytes" -gt 1048576 ]]; then
          size=$(awk "BEGIN {printf \"%.1fM\", $size_bytes/1048576}")
        elif [[ "$size_bytes" -gt 1024 ]]; then
          size=$(awk "BEGIN {printf \"%.0fK\", $size_bytes/1024}")
        else
          size="${size_bytes}B"
        fi
        md_rel="markdown/${base}.md"
        raw_rel="raw/${base}.jsonl.gz"
        if [[ -f "$RAW_DIR/${base}.jsonl.gz" ]]; then
          raw_cell="[view]($raw_rel)"
        else
          raw_cell="—"
        fi
        echo "| $date_part | \`$sess_part\` | $size | [view]($md_rel) | $raw_cell |"
      done
} > "$INDEX"

git add conversations/ >> "$LOG_FILE" 2>&1

if git diff --cached --quiet; then
  log "No changes to commit."
  log "── Copilot backup run complete (no-op) ──"
  exit 0
fi

COMMIT_MSG="archive: sync $NEW_OR_UPDATED Copilot conversation(s) $(date '+%Y-%m-%d %H:%M')"
git commit -m "$COMMIT_MSG" >> "$LOG_FILE" 2>&1 || { log "ERROR: git commit failed"; exit 1; }
log "Committed: $COMMIT_MSG"

if $PUSH_ENABLED; then
  if git push origin "$BRANCH" >> "$LOG_FILE" 2>&1; then
    log "Pushed to origin/$BRANCH"
  else
    log "ERROR: git push failed. Commit is local only."
    exit 2
  fi
fi

log "── Copilot backup run complete ──"
