#!/usr/bin/env bash
# Backup Claude conversation transcripts to a private local archive.
#
# What it does (idempotent):
#   1. Finds all .jsonl transcripts under ~/.claude/projects/
#   2. For each, copies the raw JSONL into a private archive
#   3. Runs jsonl_to_markdown.py to produce a human-readable .md
#   4. Regenerates a private INDEX.md with a sortable list
#
# Safe to run repeatedly. Existing files get overwritten with the latest copy
# (transcripts are append-only, so older content is preserved).
#
# Exit codes:
#   0 - success (with or without changes)
#   1 - setup error

set -euo pipefail

# ── Config ─────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
ARCHIVE_ROOT="${OLS_CONVERSATION_ARCHIVE_DIR:-$HOME/.ols/private/conversations}"
# Cowork/Claude desktop stores transcripts under Library/Application Support.
# Override with CLAUDE_PROJECTS_DIR env var if yours lives elsewhere.
CLAUDE_PROJECTS_DIR="${CLAUDE_PROJECTS_DIR:-$HOME/Library/Application Support/Claude/local-agent-mode-sessions}"
LOG_FILE="${LOG_FILE:-$ARCHIVE_ROOT/logs/claude-backup.log}"

# ── Logging ────────────────────────────────────────────────────────
log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg"
  echo "$msg" >> "$LOG_FILE"
}

# ── Preflight ──────────────────────────────────────────────────────
mkdir -p "$ARCHIVE_ROOT" "$(dirname "$LOG_FILE")"
chmod 700 "$ARCHIVE_ROOT" "$(dirname "$LOG_FILE")"
log "── Backup run starting ──"

if [[ ! -d "$REPO_ROOT" ]]; then
  log "ERROR: repo root not found: $REPO_ROOT"
  exit 1
fi

if [[ ! -d "$CLAUDE_PROJECTS_DIR" ]]; then
  log "ERROR: Claude projects dir not found: $CLAUDE_PROJECTS_DIR"
  log "       Set CLAUDE_PROJECTS_DIR env var if your transcripts live elsewhere."
  exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
  log "ERROR: python3 not on PATH"
  exit 1
fi

cd "$REPO_ROOT"

# ── Sync transcripts ───────────────────────────────────────────────
RAW_DIR="$ARCHIVE_ROOT/raw"
MD_DIR="$ARCHIVE_ROOT/markdown"
SCRIPTS_DIR="$REPO_ROOT/conversations/scripts"
mkdir -p "$RAW_DIR" "$MD_DIR"
chmod 700 "$RAW_DIR" "$MD_DIR"

COUNT=0
NEW_OR_UPDATED=0

# Find main-session .jsonl files only.
# Structure: .../local_<uuid>/.claude/projects/-sessions-<name>/<session-uuid>.jsonl
# Exclude:
#   - subagents/agent-*.jsonl (low-signal, work delegated from main sessions)
#   - audit.jsonl (infrastructure/permission log, not a conversation)
while IFS= read -r -d '' jsonl_file; do
  COUNT=$((COUNT + 1))

  session_id="$(basename "$jsonl_file" .jsonl)"
  # Extract the parent "-sessions-<name>" folder so we can preserve a readable label
  parent_dir="$(basename "$(dirname "$jsonl_file")")"
  # Strip the leading "-sessions-" prefix if present
  label="${parent_dir#-sessions-}"
  # Date-prefix from the file's mtime (YYYY-MM-DD)
  mtime_date="$(date -r "$jsonl_file" '+%Y-%m-%d')"
  prefix="${mtime_date}_${label}_${session_id:0:8}"

  # Raw transcripts are stored gzipped so GitHub's 100MB-per-file limit
  # doesn't block pushes. JSONL compresses ~10x.
  raw_dst="$RAW_DIR/${prefix}.jsonl.gz"
  md_dst="$MD_DIR/${prefix}.md"

  # Only re-copy + re-convert if source is newer than current raw copy
  needs_update=false
  if [[ ! -f "$raw_dst" ]]; then
    needs_update=true
  elif [[ "$jsonl_file" -nt "$raw_dst" ]]; then
    needs_update=true
  fi

  if $needs_update; then
    # gzip into the destination; -n omits filename+mtime for reproducibility
    gzip -n -c "$jsonl_file" > "$raw_dst" || {
      log "WARNING: gzip failed for $jsonl_file"
      continue
    }
    python3 "$SCRIPTS_DIR/jsonl_to_markdown.py" "$raw_dst" "$md_dst" >> "$LOG_FILE" 2>&1 || {
      log "WARNING: conversion failed for $jsonl_file"
      continue
    }
    NEW_OR_UPDATED=$((NEW_OR_UPDATED + 1))
    log "Synced: $prefix"
  fi
done < <(find "$CLAUDE_PROJECTS_DIR" -type f -name '*.jsonl' \
    -path '*/.claude/projects/-sessions-*' \
    ! -path '*/subagents/*' \
    ! -name 'audit.jsonl' \
    -print0)

log "Found $COUNT total transcript(s), $NEW_OR_UPDATED new or updated."

# ── Regenerate INDEX.md ─────────────────────────────────────────────
INDEX="$ARCHIVE_ROOT/INDEX.md"
{
  echo "# Conversation Archive Index"
  echo ""
  echo "_Auto-generated by \`backup_conversations.sh\`. Last updated: $(date '+%Y-%m-%d %H:%M:%S %Z')_"
  echo ""
  echo "| Date | Session | Size | Markdown | Raw JSONL |"
  echo "|------|---------|------|----------|-----------|"
  # List by filename (date-prefixed = chronological, newest first)
  find "$MD_DIR" -maxdepth 1 -name '*.md' -print0 2>/dev/null \
    | xargs -0 -I{} basename {} .md \
    | sort -r \
    | while IFS= read -r base; do
        md_file="$MD_DIR/${base}.md"
        date_part="${base%%_*}"
        sess_part="${base#*_}"
        size_bytes=$(wc -c < "$md_file" 2>/dev/null || echo 0)
        if [[ "$size_bytes" -gt 1048576 ]]; then
          size=$(awk "BEGIN {printf \"%.1fM\", $size_bytes/1048576}")
        elif [[ "$size_bytes" -gt 1024 ]]; then
          size=$(awk "BEGIN {printf \"%.0fK\", $size_bytes/1024}")
        else
          size="${size_bytes}B"
        fi
        raw_rel="raw/${base}.jsonl.gz"
        md_rel="markdown/${base}.md"
        echo "| $date_part | \`$sess_part\` | $size | $md_rel | $raw_rel |"
      done
} > "$INDEX"
chmod -R go-rwx "$ARCHIVE_ROOT"

log "Private archive updated at $ARCHIVE_ROOT"
log "── Backup run complete ──"
