#!/usr/bin/env bash
# Backup GitHub Copilot Chat transcripts for THIS repo into a private archive.
#
# What it does (idempotent):
#   1. Finds Copilot Chat transcripts under VS Code's workspaceStorage whose
#      workspace.json folder == this repo's root.
#   2. Copies each raw transcript (gzipped) into a private archive
#   3. Converts each to readable Markdown in the private archive
#      via copilot_jsonl_to_markdown.py
#   4. Regenerates a private INDEX.md
#
# Safe to run repeatedly. A transcript is only re-synced when its source file
# is newer than the stored copy.
#
# Exit codes: 0 success · 1 setup error

set -euo pipefail

# ── Resolve repo root from this script's own location ──────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ARCHIVE_ROOT="${OLS_CONVERSATION_ARCHIVE_DIR:-$HOME/.ols/private/conversations}"
LOG_FILE="${LOG_FILE:-$ARCHIVE_ROOT/logs/copilot-backup.log}"

# VS Code chat storage root (override with CODE_STORAGE if you use Insiders, etc.)
CODE_STORAGE="${CODE_STORAGE:-$HOME/Library/Application Support/Code/User/workspaceStorage}"

log() {
  local msg="[$(date '+%Y-%m-%d %H:%M:%S')] $*"
  echo "$msg"
  echo "$msg" >> "$LOG_FILE"
}

mkdir -p "$ARCHIVE_ROOT" "$(dirname "$LOG_FILE")"
chmod 700 "$ARCHIVE_ROOT" "$(dirname "$LOG_FILE")"
log "── Copilot backup run starting ──"

command -v python3 >/dev/null 2>&1 || { log "ERROR: python3 not on PATH"; exit 1; }
[[ -d "$REPO_ROOT/.git" ]]         || { log "ERROR: not a git repo: $REPO_ROOT"; exit 1; }
[[ -d "$CODE_STORAGE" ]]           || { log "ERROR: VS Code storage not found: $CODE_STORAGE"; exit 1; }

cd "$REPO_ROOT"

RAW_DIR="$ARCHIVE_ROOT/raw"
MD_DIR="$ARCHIVE_ROOT/markdown"
mkdir -p "$RAW_DIR" "$MD_DIR"
chmod 700 "$RAW_DIR" "$MD_DIR"

# The repo's own folder URI, as VS Code records it in workspace.json
REPO_URI="file://$REPO_ROOT"

COUNT=0
NEW_OR_UPDATED=0

# Iterate every workspace's Copilot transcript folder; keep only those whose
# workspace.json points at THIS repo. This is robust to VS Code changing the
# opaque storage hash.
while IFS= read -r -d '' tdir; do
  ws_json="$(dirname "$(dirname "$tdir")")/workspace.json"
  [[ -f "$ws_json" ]] || continue
  folder="$(python3 -c "import json,sys; print(json.load(open(sys.argv[1])).get('folder',''))" "$ws_json" 2>/dev/null || echo "")"
  # Normalize a possible trailing slash
  folder="${folder%/}"
  [[ "$folder" == "$REPO_URI" ]] || continue

  while IFS= read -r -d '' jsonl_file; do
    COUNT=$((COUNT + 1))
    session_id="$(basename "$jsonl_file" .jsonl)"
    mtime_date="$(date -r "$jsonl_file" '+%Y-%m-%d')"
    prefix="${mtime_date}_copilot_${session_id:0:8}"

    raw_dst="$RAW_DIR/${prefix}.jsonl.gz"
    md_dst="$MD_DIR/${prefix}.md"

    needs_update=false
    if [[ ! -f "$raw_dst" ]]; then
      needs_update=true
    elif [[ "$jsonl_file" -nt "$raw_dst" ]]; then
      needs_update=true
    fi

    if $needs_update; then
      gzip -n -c "$jsonl_file" > "$raw_dst" || { log "WARNING: gzip failed for $jsonl_file"; continue; }
      python3 "$SCRIPT_DIR/copilot_jsonl_to_markdown.py" "$raw_dst" "$md_dst" >> "$LOG_FILE" 2>&1 \
        || { log "WARNING: conversion failed for $jsonl_file"; continue; }
      NEW_OR_UPDATED=$((NEW_OR_UPDATED + 1))
      log "Synced: $prefix"
    fi
  done < <(find "$tdir" -maxdepth 1 -type f -name '*.jsonl' -print0)
done < <(find "$CODE_STORAGE" -maxdepth 3 -type d -name transcripts -path '*/GitHub.copilot-chat/*' -print0)

log "Found $COUNT transcript(s) for this repo, $NEW_OR_UPDATED new or updated."

# ── Regenerate private INDEX.md (covers every .md in markdown/) ──
INDEX="$ARCHIVE_ROOT/INDEX.md"
{
  echo "# Conversation Archive Index"
  echo ""
  echo "_Auto-generated by \`backup_copilot_conversations.sh\`. Last updated: $(date '+%Y-%m-%d %H:%M:%S %Z')_"
  echo ""
  echo "| Date | Session | Size | Markdown | Raw JSONL |"
  echo "|------|---------|------|----------|-----------|"
  find "$MD_DIR" -maxdepth 1 -name '*.md' -print0 2>/dev/null \
    | xargs -0 -I{} basename {} .md \
    | sort -r \
    | while IFS= read -r base; do
        md_file="$MD_DIR/${base}.md"
        date_part="${base%%_*}"
        sess_part="${base#*_}"
        size_bytes=$(wc -c < "$md_file" 2>/dev/null || echo 0)
        if [[ "$size_bytes" -gt 1048576 ]]; then
          size=$(awk "BEGIN {printf \"%.1fM\", $size_bytes/1048576}")
        elif [[ "$size_bytes" -gt 1024 ]]; then
          size=$(awk "BEGIN {printf \"%.0fK\", $size_bytes/1024}")
        else
          size="${size_bytes}B"
        fi
        md_rel="markdown/${base}.md"
        raw_rel="raw/${base}.jsonl.gz"
        if [[ -f "$RAW_DIR/${base}.jsonl.gz" ]]; then
          raw_cell="$raw_rel"
        else
          raw_cell="-"
        fi
        echo "| $date_part | \`$sess_part\` | $size | $md_rel | $raw_cell |"
      done
} > "$INDEX"
chmod -R go-rwx "$ARCHIVE_ROOT"

log "Private archive updated at $ARCHIVE_ROOT"
log "── Copilot backup run complete ──"
